version: '3.8'

networks:
  default:

services:

  test-db:
    # NOTE: Uncomment the line below if you are using Mac with m1/m2 chip
    # platform: linux/x86_64
    container_name: test-db
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_PASSWORD
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    volumes:
      - test-db-volume:/var/lib/mysql:rw
      - ./test-db:/docker-entrypoint-initdb.d/
    networks:
      - default

  test-backend:
    container_name: test-backend
    depends_on:
      - test-db
    build: ./test-backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $TEST_BACKEND_LOCAL_PORT:$TEST_BACKEND_DOCKER_PORT
    environment:
      - DB_HOST=$MYSQLDB_HOST
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_PASSWORD
      - DB_DATABASE=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./test-backend:/app
      - /app/node_modules
    networks:
      - default

  test-frontend:
    container_name: test-frontend
    depends_on:
      - test-backend
    build:
      context: ./test-frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $TEST_FRONTEND_LOCAL_PORT:$TEST_FRONTEND_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./test-frontend:/app
      - /app/node_modules
    networks:
      - default

volumes:
  test-db-volume:
